#!/bin/bash
REPO_URL="https://github.com/mvasilenko/nginx-lua-ec2.git"
branchPath=$(git symbolic-ref -q HEAD) # Something like refs/heads/myBranchName
branch=${branchPath##*/}
if [ "master" == "$branch" ]; then
        curl "http://localhost:8080/git/notifyCommit?url=$REPO_URL"
fi
